@echo off
setlocal enabledelayedexpansion
chcp 65001 >nul
title Trading Journal - Setup

echo ============================================
echo   Trading Journal - Setup Device Baru
echo ============================================
echo.

rem ---- Cek Node.js ----
where node >nul 2>nul
if errorlevel 1 (
  echo [ERROR] Node.js tidak ditemukan. Install dulu dari https://nodejs.org
  pause & exit /b 1
)
for /f "delims=" %%v in ('node -v') do set NODE_VER=%%v
echo [OK] Node.js     : %NODE_VER%

rem ---- Tanya path ----
echo.
echo Path-proyek di bawah pakai contoh dari mesin lama.
echo Kalau beda, ketik path yang benar (atau Enter untuk pakai default).
echo.

set /p BOT_DIR="Path folder proyek bot [D:\Projects\AutomationTrading\mt5-ai-trading-bot]: "
if "%BOT_DIR%"=="" set BOT_DIR=D:\Projects\AutomationTrading\mt5-ai-trading-bot

set /p PYTHON_PATH="Path python dengan MetaTrader5 [D:\HermesAgent\hermes-agent\venv\Scripts\python.exe]: "
if "%PYTHON_PATH%"=="" set PYTHON_PATH=D:\HermesAgent\hermes-agent\venv\Scripts\python.exe

set /p TERMINAL_PATH="Path terminal64.exe [C:\Program Files\MetaTrader 5\terminal64.exe]: "
if "%TERMINAL_PATH%"=="" set TERMINAL_PATH=C:\Program Files\MetaTrader 5\terminal64.exe

set /p TJ_PORT="Port journal [8500]: "
if "%TJ_PORT%"=="" set TJ_PORT=8500

rem ---- Tulis .env ----
(
  echo # Generated by setup.bat
  echo MT5_SYNC_SCRIPT=%BOT_DIR%\mt5_sync.py
  echo MT5_SYNC_PYTHON=%PYTHON_PATH%
  echo TJ_URL=http://127.0.0.1:%TJ_PORT%
  echo MT5_TERMINAL_PATH=%TERMINAL_PATH%
  echo AUTO_SYNC_SECONDS=0
) > ".env"
echo [OK] .env dibuat

rem ---- Cek Python + MetaTrader5 ----
echo.
echo Mengecek Python...
"%PYTHON_PATH%" -c "import sys; print('[OK] Python', sys.version.split()[0])" >nul 2>nul
if errorlevel 1 (
  echo [WARN] Python tidak ditemukan di %PYTHON_PATH%
  echo        Path .env sudah diisi, tapi pastikan python-nya benar.
) else (
  "%PYTHON_PATH%" -c "import MetaTrader5" >nul 2>nul
  if errorlevel 1 (
    echo [INFO] MetaTrader5 belum terinstall, install sekarang...
    "%PYTHON_PATH%" -m pip install MetaTrader5
    if errorlevel 1 echo [WARN] Gagal install MetaTrader5 - cek internet/koneksi.
  ) else (
    echo [OK] MetaTrader5 package tersedia
  )
)

rem ---- Cek terminal MT5 ----
if exist "%TERMINAL_PATH%" (
  echo [OK] Terminal MT5 ditemukan: %TERMINAL_PATH%
) else (
  echo [WARN] Terminal MT5 tidak ditemukan di %TERMINAL_PATH%
  echo        Pastikan MetaTrader 5 terinstall dan sudah login akun.
)

rem ---- npm install + build ----
echo.
echo Install dependency npm...
call npm install
if errorlevel 1 ( echo [ERROR] npm install gagal & pause & exit /b 1 )

echo.
echo Build proyek...
call npm run build
if errorlevel 1 ( echo [ERROR] build gagal & pause & exit /b 1 )

echo.
echo ============================================
echo   Setup selesai!
echo.
echo   Jalankan:  npm start -- -p %TJ_PORT%
echo   Buka:      http://127.0.0.1:%TJ_PORT%
echo   Lalu di menu Pengaturan aktifkan Auto Sync.
echo ============================================
pause
